require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OldGamesController do

  # This should return the minimal set of attributes required to create a valid
  # OldGame. As you add validations to OldGame, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "game_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OldGamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all old_games as @old_games" do
      old_game = OldGame.create! valid_attributes
      get :index, {}, valid_session
      assigns(:old_games).should eq([old_game])
    end
  end

  describe "GET show" do
    it "assigns the requested old_game as @old_game" do
      old_game = OldGame.create! valid_attributes
      get :show, {:id => old_game.to_param}, valid_session
      assigns(:old_game).should eq(old_game)
    end
  end

  describe "GET new" do
    it "assigns a new old_game as @old_game" do
      get :new, {}, valid_session
      assigns(:old_game).should be_a_new(OldGame)
    end
  end

  describe "GET edit" do
    it "assigns the requested old_game as @old_game" do
      old_game = OldGame.create! valid_attributes
      get :edit, {:id => old_game.to_param}, valid_session
      assigns(:old_game).should eq(old_game)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OldGame" do
        expect {
          post :create, {:old_game => valid_attributes}, valid_session
        }.to change(OldGame, :count).by(1)
      end

      it "assigns a newly created old_game as @old_game" do
        post :create, {:old_game => valid_attributes}, valid_session
        assigns(:old_game).should be_a(OldGame)
        assigns(:old_game).should be_persisted
      end

      it "redirects to the created old_game" do
        post :create, {:old_game => valid_attributes}, valid_session
        response.should redirect_to(OldGame.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved old_game as @old_game" do
        # Trigger the behavior that occurs when invalid params are submitted
        OldGame.any_instance.stub(:save).and_return(false)
        post :create, {:old_game => { "game_id" => "invalid value" }}, valid_session
        assigns(:old_game).should be_a_new(OldGame)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OldGame.any_instance.stub(:save).and_return(false)
        post :create, {:old_game => { "game_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested old_game" do
        old_game = OldGame.create! valid_attributes
        # Assuming there are no other old_games in the database, this
        # specifies that the OldGame created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OldGame.any_instance.should_receive(:update_attributes).with({ "game_id" => "1" })
        put :update, {:id => old_game.to_param, :old_game => { "game_id" => "1" }}, valid_session
      end

      it "assigns the requested old_game as @old_game" do
        old_game = OldGame.create! valid_attributes
        put :update, {:id => old_game.to_param, :old_game => valid_attributes}, valid_session
        assigns(:old_game).should eq(old_game)
      end

      it "redirects to the old_game" do
        old_game = OldGame.create! valid_attributes
        put :update, {:id => old_game.to_param, :old_game => valid_attributes}, valid_session
        response.should redirect_to(old_game)
      end
    end

    describe "with invalid params" do
      it "assigns the old_game as @old_game" do
        old_game = OldGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OldGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => old_game.to_param, :old_game => { "game_id" => "invalid value" }}, valid_session
        assigns(:old_game).should eq(old_game)
      end

      it "re-renders the 'edit' template" do
        old_game = OldGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OldGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => old_game.to_param, :old_game => { "game_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested old_game" do
      old_game = OldGame.create! valid_attributes
      expect {
        delete :destroy, {:id => old_game.to_param}, valid_session
      }.to change(OldGame, :count).by(-1)
    end

    it "redirects to the old_games list" do
      old_game = OldGame.create! valid_attributes
      delete :destroy, {:id => old_game.to_param}, valid_session
      response.should redirect_to(old_games_url)
    end
  end

end
